### ISSUE TITLE
picking up dream journal crashes game

### ISSUE THREAD

**Issue by Eos109** [daedalus4096/PrimalMagick#233] opened 2023-11-23 22:01 UTC
this problem again, version 4.0.8
to recreate you NEED to use a server and connecting to it from a client on a different machine. picking up the dream journal crashes the game
```
23.11 21:46:32 [Server] INFO java.util.NoSuchElementException: No value present
23.11 21:46:32 [Server] INFO 	at java.base/java.util.Optional.orElseThrow(Optional.java:377)
23.11 21:46:32 [Server] INFO 	at TRANSFORMER/primalmagick@4.0.8/com.verdantartifice.primalmagick.common.books.BookHelper.getTitleTextInner(BookHelper.java:57)
23.11 21:46:32 [Server] INFO 	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
23.11 21:46:32 [Server] INFO 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.Util$10.apply(Util.java:706)
23.11 21:46:32 [Server] INFO 	at TRANSFORMER/primalmagick@4.0.8/com.verdantartifice.primalmagick.common.books.BookHelper.getTitleText(BookHelper.java:48)
23.11 21:46:32 [Server] INFO 	at TRANSFORMER/primalmagick@4.0.8/com.verdantartifice.primalmagick.common.items.books.StaticBookItem.m_7626_(StaticBookItem.java:191)
23.11 21:46:32 [Server] INFO 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.item.ItemStack.m_41786_(ItemStack.java:580)
23.11 21:46:32 [Server] INFO 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.item.ItemStack.m_41611_(ItemStack.java:911)
23.11 21:46:32 [Server] INFO 	at TRANSFORMER/createsweetsandtreets@1.0.0/net.mcreator.createsweetsandtreets.procedures.SugarCookiePropertyValueProviderProcedure.execute(SugarCookiePropertyValueProviderProcedure.java:30)
23.11 21:46:32 [Server] INFO 	at TRANSFORMER/createsweetsandtreets@1.0.0/net.mcreator.createsweetsandtreets.procedures.SugarCookiePropertyValueProviderProcedure.onPlayerTick(SugarCookiePropertyValueProviderProcedure.java:19)
23.11 21:46:32 [Server] INFO 	at TRANSFORMER/createsweetsandtreets@1.0.0/net.mcreator.createsweetsandtreets.procedures.__SugarCookiePropertyValueProviderProcedure_onPlayerTick_PlayerTickEvent.invoke(.dynamic)
23.11 21:46:32 [Server] INFO 	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
23.11 21:46:32 [Server] INFO 	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
23.11 21:46:32 [Server] INFO 	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
23.11 21:46:32 [Server] INFO 	at TRANSFORMER/forge@47.2.1/net.minecraftforge.event.ForgeEventFactory.onPlayerPostTick(ForgeEventFactory.java:920)
23.11 21:46:32 [Server] INFO 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.player.Player.m_8119_(Player.java:285)
23.11 21:46:32 [Server] INFO 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:467)
23.11 21:46:32 [Server] INFO 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:262)
23.11 21:46:32 [Server] INFO 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.Connection.m_129483_(Connection.java:263)
23.11 21:46:32 [Server] INFO 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142)
23.11 21:46:32 [Server] INFO 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:907)
23.11 21:46:32 [Server] INFO 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:283)
23.11 21:46:32 [Server] INFO 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814)
23.11 21:46:32 [Server] INFO 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661)
23.11 21:46:32 [Server] INFO 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251)
23.11 21:46:32 [Server] INFO 	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by daedalus4096** [comment] 2023-11-24 02:45
Looks like it's breaking in a different way this time, at least.  It appears to be the result of a negative mod interaction with the Sweets and Treats addon for Create.  Why that mod would be interacting with mine is beyond me, but you could try disabling it to work around the issue while I work on a fix for Primal Magick if you like.

**Comment by Eos109** [comment] 2023-11-24 05:50
I'll try that later when I got time again

**Comment by daedalus4096** [comment] 2023-11-24 06:58
Okay, I was able to reproduce the crash this time, so I'm pretty sure it's properly fixed now.  The fix will be included in the next release, currently planned as 4.0.9.  Thanks for the report!

**Closed** 2023-11-24 06:58 UTC
Labels: bug
