### ISSUE TITLE
[Bug] Crash on an attempt to create a grimoire

### ISSUE THREAD

**Issue by morsmores** [daedalus4096/PrimalMagick#100] opened 2022-06-02 20:33 UTC
Holding down right click with the mundane wand, at the moment it should make a grimoire, it instead dies.

I'm sure it's caused by some bad interaction with another mod in there, but it might be worth knowing what has a bad interaction, at least?

Crash Report:
[crash-2022-06-02_16.23.19-server.txt](https://github.com/daedalus4096/PrimalMagick/files/8827648/crash-2022-06-02_16.23.19-server.txt)

**Comment by morsmores** [comment] 2022-06-02 22:42
Tested:
- Creative world, no other magic mods used.
- Removed Mana and Artifice.
- Updated Forge version (1.25 to 1.31).
- Removed Quark and dependents.
- Removed Vampirism.
- Removed Nature's Aura.
- Removed Malum.
- Removed Dragon Survival.
- Removed Ars Nouveau and addons.
- Removed Apotheosis.
- Removed Hex Casting.
- Removed EvilCraft.
Still crashes. Further testing will be done as a follow-up.

**Comment by daedalus4096** [comment] 2022-06-03 01:34
This looks like a mod compatibility issue with a mod called Effortless Building.  I'm not sure yet *why* the two don't get along, but you should be able to disable that if you want to continue playing Primal Magick in the meantime.

**Comment by morsmores** [comment] 2022-06-03 01:39
> 

You're a lifesaver, I was slightly more than halfway through dragging out my mods one by one.

**Comment by daedalus4096** [comment] 2022-06-03 21:40
I wasn't actually able to reproduce this issue, either on single-player or multi-player.  That said, I walked through the code some and found what I think is the source of the problem.  I've added a fix, but because I was never able to replicate the problem I can't test it.  This fix will be in upcoming release v2.1.2, so please try again once that's out.  Thank you for your patience.

**Comment by daedalus4096** [comment] 2022-06-26 01:47
I haven't heard any reports of this issue reproducing since v2.1.2 was released, so I'm going to assume that it's fixed for now.  Should you encounter this issue again, please file a new ticket.  Thanks for the report!

**Closed by daedalus4096** 2022-06-26 01:47 UTC
Labels: bug
