### ISSUE TITLE
Server disconnects players while playing on LAN

### ISSUE THREAD

**Issue by prostolyubo** [daedalus4096/PrimalMagick#276] opened 2024-07-08 12:28 UTC
When I play in singleplayer everything is fine. When I make the game open to lan and another player joins they immediatelly get disconnected. There are no errors on the server, there is only a warning on the client that tried to connect:
`Client disconnected with reason: Internal Exception: net.minecraft.server.v1_14_R1.ResourceKeyInvalidException: Non [a-z0-9/._-] character in path of location: minecraft:\u0001\u0004\u0001\u0001`

Minecraft 1.20.4 Forge 49.1.0 PrimalMagick 4.2.0-beta

I scoured through the files with regexp but didn't mange to find any file that has a non [a-z0-9/._-] character in it nor empty value after "minecraft:". Same with jsons: all the references seem to have a correct format.

The issue is not 100% reproductible. I managed to connect three times (out of dozens) when I was trying to figure out exactly what helped or what really causes the issue.

**Comment by daedalus4096** [comment] 2024-09-17 20:43
Despite my best efforts, I've been unable to reproduce this issue. If it occurs for you again and you can acquire a log file or crash/disconnect report that I can examine in more detail, please open a new ticket. In the meantime, I'm going to close this.

**Closed by daedalus4096** 2024-09-17 20:43 UTC
Labels: bug
