### ISSUE TITLE
Analysis Table to Arcane Workbench crash report

### ISSUE THREAD

**Issue by OblivionCultist** [daedalus4096/PrimalMagick#199] opened 2023-10-01 17:30 UTC
With String in hand opened the Analysis Table interface, closed the interface and right clicked on Arcane Workbench with string still in hand and had a crash. Might be related to the previous crash that is fixed next update but including here just for completeness sake.

[crash-2023-10-01_10.18.40-client.txt](https://github.com/daedalus4096/PrimalMagick/files/12777776/crash-2023-10-01_10.18.40-client.txt)

**Comment by daedalus4096** [comment] 2023-10-01 19:05
Yeah, this looks like a duplicate of #196 which you opened before.  This should be fixed in the next version, which I'm hoping to release next weekend.  Thanks for the report nonetheless.

**Closed by daedalus4096** 2023-10-01 19:05 UTC
