### ISSUE TITLE
Game doesn't render loading chunks while primal magick

### ISSUE THREAD

**Issue by SpinoFTW** [daedalus4096/PrimalMagick#142] opened 2023-06-14 17:50 UTC
Hello I'm using primal magick 3.2.1 and get it error from immersive engineering about affinities https://pastebin.com/chmyxHqs is the pastebin for the error

**Comment by SpinoFTW** [comment] 2023-06-14 17:51
seems like removing primal magick fixes the issue

**Comment by daedalus4096** [comment] 2023-07-23 20:32
If I'm understanding your bug report correctly, it sounds like this is a duplicate of another bug, the one that causes lag spikes when getting affinity values when certain item-heavy mods are installed.  This should be fixed in the upcoming 1.20.1 release.  Should you continue to encounter it, please file a new ticket.  Thanks!

**Closed by daedalus4096** 2023-07-23 20:32 UTC
