### ISSUE TITLE
Casting an offensive spell from your offhand at an entity's back with a Farmer's Delight Backstabbing knife in your main hand causes crash

### ISSUE THREAD

**Issue by Not-February** [daedalus4096/PrimalMagick#137] opened 2022-12-11 07:46 UTC
I really am not sure which mod is to blame, so I'm reporting it to both issue trackers. [Here's a link to the Farmer's Delight issue](https://github.com/vectorwing/FarmersDelight/issues/603).

I have successfully replicated this issue with nothing but Forge, FD and PM installed.

latest.log: https://gist.github.com/Not-February/30d293dc610cc60f4883ad1b1e8dbacc
crash log: https://gist.github.com/Not-February/5e32d1290a35f897384cbbdbd252be2a

MC 1.19.2
Forge 43.1.52
Primal Magick 3.2.1
Farmer's Delight 1.2.0

**Comment by daedalus4096** [comment] 2023-07-23 20:54
I'm not able to reproduce this issue using Farmer's Delight 1.2.2a and the upcoming 1.20.1 release of Primal Magick.  It looks like whatever the Farmer's Delight author did in the meantime fixed the issue, so I'm going to close this for now.  If you encounter the crash again, please open a new ticket.  Thank you for the report!

**Closed by daedalus4096** 2023-07-23 20:54 UTC
